# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-26 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('emailid', models.EmailField(max_length=254)),
            ],
        ),
    ]
